audio_transformer:
  ## single layer
  dropout: 0.1
  embed_dim: 128
  ffn_embed_dim: 512
  
  ## transformer encoder
  num_layers: 2

video_transformer:
  ## single layer
  dropout: 0.1
  embed_dim: 512
  ffn_embed_dim: 1024
  
  ## transformer encoder
  num_layers: 0

va_model:
  negative_samples: 100
  available_samples: 3339

dataset:
  train_dir: E:\\清华\\大三秋\\视听信息系统导论\\大作业\\Train
  test_dir: E:\\清华\\大三秋\\视听信息系统导论\\大作业\\Test\\Clean


